# Generated by Django 5.0.6 on 2024-10-04 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_friends_blocked_friends_blocker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='blocker',
        ),
        migrations.CreateModel(
            name='BLOCKER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queryset_blocked', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queryset_blocker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
