SUCCESS_MSG = {
    "1" : "Invitation sent successfully! The user will receive a notification shortly.",
    "2" : "Invitation accepted! You are now friends.",
    "3" : "You have successfully declined the friend request.",
    "4" : "Success! You are no longer friends !",
    "5" : "User has been blocked successfully.",
    "6" : "User has been unblocked successfully.",
}

ERROR_MSG = {
    "1" : "Sorry, we couldn't find an account for that username.",
    "2" : "The username cannot contain special characters.",
    "3" : 'Invalid request: Username is required to complete this action.',
    "4" : 'User cannot send a request to themselves.',
    "5" : 'You have already sent an invitation to this user.',
    "6" : 'You have already recived an invitation from this user.',
    "7" : 'User cannot accept a request to themselves.',
    "8" : 'There is no invitation request from the selected user.',
    "9" : "You cannot decline an invitation for yourself.",
    "10" : "Action Not Allowed : You cannot see a friend status for yourself.",
    "11" : "Action Not Allowed !",
    "12" : "No request to be accepted.",
    "13" : "You can't send an invitation because you're already friends.",
    "14" : "Action Not Allowed : because you're already friends.",
    "15" : 'Two-Factor Authentication (2FA) is required.',
    "16" : "Action Not Allowed : because you're already did block this user.",
    "17" : "Action Not Allowed : you cannot block yourself !",
    "18" : "Action Not Allowed : you cannot unblock yourself !",
    "19" : "you have previously blocked this user.",
    "20" : "this user has previously blocked you.",
}