version: '2.29.2'

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    
    image: backend
    container_name: backend
    depends_on:
      - db
    volumes:
      - ./backend/source:/server
    networks:
      - mynetwork
    restart: always
    env_file:
      - .env

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - .env
    volumes:
      - ./Frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - mynetwork
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    build: ./nginx
    ports:
      - "8443:443"
    volumes:
      - ./backend/source/media:/media
    networks:
      - mynetwork
    depends_on:
      - backend
      - frontend

  # redis:
  #   build:
  #     context: ./tools/Redis
  #     dockerfile: Dockerfile
    
  #   container_name: redis
    
  #   networks:
  #     - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
