version: '2.29.2'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    
    image: backend
    container_name: backend

    depends_on:
      - db
    ports:
      - 9003:8001
    volumes:
      - ./backend/source:/server
    networks:
      - mynetwork
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx
    container_name: nginx
    build: ./nginx
    ports:
      - "443:443"
    networks:
      - mynetwork
    depends_on:
      - backend
      - frontend
  
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    # environment:
    #   NEXT_PUBLIC_API_URL: "http://localhost:9003" # change this to your local ip or use localhost
    ports:
      - 9001:3000
    volumes:
      - ./Frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - mynetwork
    restart: always

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  # redis:
  #   build:
  #     context: ./tools/Redis
  #     dockerfile: Dockerfile
    
  #   container_name: redis
    
  #   networks:
  #     - mynetwork

    

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
