version: '2.29.2'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    
    image: django
    container_name: django

    # depends_on:
    #   - redis
    ports:
      - 9003:8001
    volumes:
      - ./backend/source:/server
    networks:
      - mynetwork
  
  nextjs:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: nextjs
    # environment:
    #   NEXT_PUBLIC_API_URL: "http://localhost:9003" # change this to your local ip or use localhost
    ports:
      - 9001:3000
    volumes:
      - ./Frontend:/app
      - /app/node_modules
      - /app/.next
    # command: npm run start

  # redis:
  #   build:
  #     context: ./tools/Redis
  #     dockerfile: Dockerfile
    
  #   container_name: redis
    
  #   networks:
  #     - mynetwork
    

networks:
  mynetwork:
    driver: bridge