# Generated by Django 5.0.6 on 2024-09-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='picture',
            field=models.ImageField(blank=True, default='avatars/unknown.jpg', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='register',
            name='token_chat',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='register',
            name='token_game',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='register',
            name='token_notify',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
    ]
