# Generated by Django 5.0.6 on 2024-09-21 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_register_password_sec'),
        ('security', '0002_security_delete_password_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='SECURE',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='security.security'),
        ),
    ]
