# Generated by Django 5.0.6 on 2024-09-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_register_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='photo_url',
            field=models.URLField(default='http://127.0.0.1:9003/register/media/avatars/unknown.jpg'),
        ),
    ]
