# Generated by Django 5.0.6 on 2024-09-14 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('account', models.CharField(blank=True, default='normal', max_length=150)),
                ('activate_token', models.CharField(blank=True, max_length=150)),
                ('is_online', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=180)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('token_game', models.CharField(blank=True, max_length=40, unique=True)),
                ('token_notify', models.CharField(blank=True, max_length=40, unique=True)),
                ('token_chat', models.CharField(blank=True, max_length=40, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile_Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.BooleanField(default=False)),
                ('on_login', models.BooleanField(default=False)),
                ('code_2fa', models.IntegerField(default=0)),
                ('retry_later', models.IntegerField(default=0)),
                ('next_retry_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('t_match', models.IntegerField(default=0)),
                ('url_picture', models.URLField(max_length=40, null=True)),
                ('level', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default='1', max_length=2)),
                ('achievements', models.CharField(default='Bronze', max_length=150)),
                ('avatar', models.ImageField(blank=True, default='avatars/unknown.jpg', upload_to='avatars/')),
                ('xp_total', models.IntegerField(default=0)),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('list', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='friends.friendslist')),
                ('secutity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile_security')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('retry_counter', models.IntegerField(default=0)),
                ('send_counter', models.IntegerField(default=0)),
                ('send_retry_time', models.DateTimeField(blank=True, null=True)),
                ('verify_retry_time', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
