# Generated by Django 5.0.6 on 2024-09-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STATICS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
                ('total_match', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('achievements', models.IntegerField(default=1)),
                ('xp_total', models.IntegerField(default=0)),
            ],
        ),
    ]
