# Generated by Django 5.0.6 on 2024-09-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statics',
            name='rank',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
