# Generated by Django 5.0.6 on 2024-09-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_statics_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statics',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
