# Generated by Django 5.0.6 on 2024-12-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_statics_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='statics',
            name='level_progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statics',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
