# Generated by Django 5.0.6 on 2024-12-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_statics_level_progress_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statics',
            name='last_match',
            field=models.CharField(default='Unnamed', max_length=10),
        ),
    ]
