# Generated by Django 5.0.6 on 2025-01-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_statics_last_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statics',
            name='last_match',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
