# Generated by Django 5.0.6 on 2025-01-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_statics_last_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statics',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='statics',
            name='rank',
        ),
    ]
