# Generated by Django 5.0.6 on 2024-10-15 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_1', models.CharField(blank=True, max_length=60, null=True)),
                ('token_2', models.CharField(blank=True, max_length=60, null=True)),
                ('date_match1', models.DateTimeField(auto_now_add=True)),
                ('token_winner1', models.CharField(blank=True, max_length=60, null=True)),
                ('token_3', models.CharField(blank=True, max_length=60, null=True)),
                ('token_4', models.CharField(blank=True, max_length=60, null=True)),
                ('date_match2', models.DateTimeField(blank=True, null=True)),
                ('token_winner2', models.CharField(blank=True, max_length=60, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('king', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_king', to=settings.AUTH_USER_MODEL)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions_p1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions_p2', to=settings.AUTH_USER_MODEL)),
                ('player3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions_p3', to=settings.AUTH_USER_MODEL)),
                ('player4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions_p4', to=settings.AUTH_USER_MODEL)),
                ('winner_match1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_match1', to=settings.AUTH_USER_MODEL)),
                ('winner_match2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_match2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
