# Generated by Django 5.0.6 on 2024-10-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournement', '0002_competition_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_match1',
            field=models.DateTimeField(blank=True),
        ),
    ]
