# Generated by Django 5.0.6 on 2024-10-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournement', '0003_alter_competition_date_match1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_match1',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
