# Generated by Django 5.0.6 on 2024-10-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournement', '0004_alter_competition_date_match1'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='friends',
            field=models.BooleanField(default=False),
        ),
    ]
