# Generated by Django 5.0.6 on 2024-10-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournement', '0005_competition_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='date_end',
            new_name='date_starts',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='date_match1',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='date_match2',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='king',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='player4',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='token_1',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='token_2',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='token_3',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='token_4',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='token_winner1',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='token_winner2',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='winner_match1',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='winner_match2',
        ),
        migrations.AddField(
            model_name='competition',
            name='date_ends',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='structure',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
