# Generated by Django 5.0.6 on 2024-10-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournement', '0006_rename_date_end_competition_date_starts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_ends',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date_starts',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
