# Generated by Django 5.0.6 on 2024-10-30 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournement', '0007_alter_competition_date_ends_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='date_ends',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='date_starts',
            new_name='date_start',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='structure',
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('date_start', models.DateTimeField(auto_now_add=True, null=True)),
                ('structure', models.JSONField(blank=True, null=True)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='final',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final', to='tournement.rooms'),
        ),
        migrations.AddField(
            model_name='competition',
            name='smi1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smi1', to='tournement.rooms'),
        ),
        migrations.AddField(
            model_name='competition',
            name='smi2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smi2', to='tournement.rooms'),
        ),
    ]
