# Generated by Django 5.0.6 on 2024-09-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_security_delete_password_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='on_login',
            field=models.BooleanField(default=False),
        ),
    ]
