# Generated by Django 5.0.6 on 2025-01-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_security_token_security_token_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='on_login',
        ),
        migrations.AddField(
            model_name='security',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
