# Generated by Django 5.0.6 on 2025-08-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_remove_security_on_login_security_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='code',
        ),
        migrations.RemoveField(
            model_name='security',
            name='retry_counter',
        ),
        migrations.RemoveField(
            model_name='security',
            name='retry_time',
        ),
        migrations.RemoveField(
            model_name='security',
            name='send_counter',
        ),
        migrations.RemoveField(
            model_name='security',
            name='token',
        ),
        migrations.RemoveField(
            model_name='security',
            name='token_time',
        ),
    ]
