# Generated by Django 5.0.6 on 2024-12-19 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('winner_score', models.IntegerField(default=0, null=True)),
                ('loser_score', models.IntegerField(default=0, null=True)),
                ('loser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='games_lost', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='games_won', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
