# Generated by Django 5.0.6 on 2025-01-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time_ago',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
