# Generated by Django 5.0.6 on 2025-01-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0002_game_time_ago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_ago',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
