# Generated by Django 5.0.6 on 2025-01-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0003_alter_game_time_ago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='time_ago',
        ),
    ]
