# Generated by Django 5.0.6 on 2025-01-12 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_gameinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvite',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
