# Generated by Django 5.0.6 on 2024-09-20 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_register_picture_register_token_chat_and_more'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='PASSWORD_SEC',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='security.password_security'),
        ),
    ]
