# Generated by Django 5.0.6 on 2024-09-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_register_password_sec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='PASSWORD_SEC',
        ),
    ]
