# Generated by Django 5.0.6 on 2024-09-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_register_secure'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
