# Generated by Django 5.0.6 on 2024-09-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_register_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='is_active',
        ),
    ]
