# Generated by Django 5.0.6 on 2024-09-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('register', '0007_remove_register_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='DETAILS',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.statics'),
        ),
    ]
