# Generated by Django 5.0.6 on 2024-10-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_register_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='token_game',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
