# Generated by Django 5.0.6 on 2025-01-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_register_token_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='photo_url',
            field=models.URLField(default='http://10.13.7.9:9003/register/media/avatars/unknown.jpg'),
        ),
    ]
