# Generated by Django 5.0.6 on 2025-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_register_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='photo_url',
<<<<<<< HEAD
            field=models.URLField(default='http://10.13.7.9:9003/media/avatars/unknown.jpg'),
=======
            field=models.URLField(default='http://10.13.2.18:9003/media/avatars/unknown.jpg'),
>>>>>>> origin/main
        ),
    ]
