# Generated by Django 5.0.6 on 2025-01-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_alter_register_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='photo_url',
            field=models.URLField(default='http://10.13.2.18:9003/media/avatars/unknown.jpeg'),
        ),
        migrations.AlterField(
            model_name='register',
            name='picture',
            field=models.ImageField(blank=True, default='avatars/unknown.jpeg', upload_to='avatars/'),
        ),
    ]
