# Generated by Django 5.0.6 on 2025-01-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_alter_register_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='provider_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
