# Generated by Django 5.0.6 on 2025-01-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_register_provider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
