# Generated by Django 5.0.6 on 2025-01-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_alter_register_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='photo_url',
            field=models.URLField(default='http://10.13.7.9:9003/media/avatars/unknown.jpeg'),
        ),
    ]
