# Generated by Django 5.0.6 on 2025-01-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_alter_register_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='photo_url',
            field=models.URLField(default='https://10.13.3.15:8443/media/avatars/unknown.jpeg'),
        ),
    ]
