# Generated by Django 5.0.6 on 2025-01-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0028_alter_register_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='photo_url',
            field=models.URLField(default='https://10.13.7.10:8443/media/avatars/unknown.jpeg'),
        ),
    ]
