# Generated by Django 5.0.6 on 2024-09-27 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NOTIFY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.BooleanField(default=False)),
                ('content', models.CharField(choices=[('0', 'NONE'), ('1', 'MESSAGE'), ('2', 'INVITATION'), ('3', 'ACCEPT'), ('4', 'DECLINE'), ('5', 'UNFRIEND')], default='0', max_length=2)),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recive_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
