# Generated by Django 5.0.6 on 2024-09-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='content',
            field=models.CharField(default='NONE', max_length=20),
        ),
    ]
