# Generated by Django 5.0.6 on 2025-01-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notify_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notify',
            options={'ordering': ['-time']},
        ),
    ]
