# Generated by Django 5.0.6 on 2024-09-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_register_password_sec'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SECURITY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_2fa', models.IntegerField(default=0)),
                ('activate', models.BooleanField(default=False)),
                ('code', models.IntegerField(default=0)),
                ('send_counter', models.IntegerField(default=0)),
                ('retry_counter', models.IntegerField(default=0)),
                ('retry_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PASSWORD_SECURITY',
        ),
    ]
