# Generated by Django 5.0.6 on 2024-09-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_security_on_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='token',
            field=models.CharField(blank=True, max_length=61, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='security',
            name='token_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
