# Generated by Django 5.0.6 on 2024-09-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BLOCKER',
        ),
    ]
